# Generated by Django 3.0.6 on 2020-06-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creative_blog', '0002_auto_20200605_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclassphoto',
            name='master_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='creative_blog.MasterClass'),
        ),
        migrations.AlterField(
            model_name='masterclassvideo',
            name='master_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='creative_blog.MasterClass'),
        ),
    ]
