# Generated by Django 3.0.6 on 2020-06-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20200601_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=None, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_date',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
