# Generated by Django 3.0.6 on 2020-06-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20200602_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='forum_nickname',
            field=models.CharField(default='user_8979974', max_length=75),
        ),
    ]
