# Generated by Django 3.0.6 on 2020-06-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_auto_20200602_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forum_nickname',
            field=models.CharField(default='user_3599146', max_length=75),
        ),
    ]
