# Generated by Django 3.0.6 on 2020-06-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_auto_20200603_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forum_nickname',
            field=models.CharField(default='user_8709326', max_length=75),
        ),
    ]
