# Generated by Django 3.0.6 on 2020-06-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_auto_20200603_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forum_nickname',
            field=models.CharField(default='user_3928110', max_length=75),
        ),
    ]
