# Generated by Django 3.0.6 on 2020-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0017_auto_20200603_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='forum_nickname',
            field=models.CharField(default='user_nickname', max_length=75),
        ),
    ]
