# Generated by Django 3.0.6 on 2020-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0018_auto_20200603_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_filename',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
    ]
