# Generated by Django 3.0.6 on 2020-06-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0019_user_photo_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo_filename',
            new_name='photo',
        ),
    ]
