# Generated by Django 3.0.6 on 2020-06-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_shop', '0002_auto_20200602_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
