# Generated by Django 3.0.6 on 2020-06-02 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creative_shop', '0004_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
