# Generated by Django 3.0.6 on 2020-06-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creative_shop', '0005_product_photo_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', related_query_name='products', to='creative_shop.ProductCategory'),
        ),
    ]
